docs(flowchart) add flowchart
emmett00x/docs pull request #104
Opened 2023-11-30 14:20 UTC by Contessafry

2023-12-01 10:11 UTC, riccardogenova-bitrocket-studio requested changes

2023-12-01 10:11 UTC, riccardogenova-bitrocket-studio commented on keywords.md
> +- **Agile**: Metodologia di sviluppo software che enfatizza la consegna incrementale, collaborazione, adattabilità, e riflessione continua. -**Scrum**: Un framework agile che organizza lo sviluppo so
Mandare a capo

2023-12-01 10:11 UTC, riccardogenova-bitrocket-studio commented on keywords.md
>  - **Hypervisor**: Un software che consente l'esecuzione di macchine virtuali su un sistema host, gestendo l'accesso alle risorse hardware.
Rimuovere keywords

2023-12-02 16:58 UTC, Contessafry commented
ho fatto il mio esempio di flowchart, ma non riesco ad avviare una nuova pull request

2024-02-24 15:51 UTC, closed without merging